version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch-01
      - discovery.seed_hosts=elasticsearch-01
      - cluster.initial_master_nodes=elasticsearch-01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  geomet-data-registry:
    container_name: geomet-data-registry
    env_file:
      - dev.env
    environment:
      - GDR_LOGGING_LOGLEVEL: "${GDR_LOGGING_LOGLEVEL}"
      - GDR_LOGGING_LOGFILE: "${GDR_LOGGING_LOGFILE}"
      - GDR_CONFIG: "${GDR_CONFIG}"
      - GDR_BASEDIR: "${GDR_BASEDIR}"
      - GDR_DATADIR: "${GDR_DATADIR}"
      - GDR_URL: "${GDR_URL}"
      - GDR_TILEINDEX_TYPE: "${GDR_TILEINDEX_TYPE}"
      - GDR_TILEINDEX_BASEURL: "${GDR_TILEINDEX_BASEURL}"
      - GDR_TILEINDEX_NAME: "${GDR_TILEINDEX_NAME}"
      - GDR_STORE_TYPE: "${GDR_STORE_TYPE}"
      - GDR_STORE_URL: "${GDR_STORE_URL}"
      - XDG_CACHE_HOME: "${XDG_CACHE_HOME}"
    build:
      context: .
    entrypoint: ['/home/geoadm/start.sh']
