version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch-01
      - discovery.seed_hosts=elasticsearch-01
      - cluster.initial_master_nodes=elasticsearch-01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200

  redis:
    container_name: redis
    image: redis
    ports:
      - 6380:6379

  geomet-data-registry:
    container_name: geomet-data-registry-image
    build:
      context: .
    entrypoint: ['echo', 'hi']
